######################################################################################################################################################

resource_types:
- name: helm
  type: docker-image
  source:
    repository: geek876/concourse-helm3-resource
    tag: v1.20.6

######################################################################################################################################################

resources:

- name: helm-deploy-((service))
  type: helm
  icon: helm
  source:
    repos:
      - name: stable
        url: https://charts.helm.sh/stable

- name: helm-deployment
  type: helm
  icon: helm
  source:
    branch: master
    uri: https://github.com/geek876/helm-deployment.git

######################################################################################################################################################

jobs:
- name: ((service))
  plan:
  - get: helm-deployment
    trigger: true
  - put: helm-deploy-(( service ))
    params:
      chart: ((chart))
      version: ((chart-version))
      values: helm-deployment/((value-file))
      release: ((service))
      namespace: ((namespace))
      override_values: ((secrets))

######################################################################################################################################################